### ISSUE TITLE
Question regarding equation (6) in the paper

### ISSUE THREAD

**Issue by melhashash** [XTU-PR-LAB/SaNerf#1]
Hi,

Thanks for sharing the code.

Equation (6) in the paper should be a photometric loss. However, after checking the codes, I found that this line compute reprojection error not a photometric error. Am I missing something?

https://github.com/XTU-PR-LAB/SaNerf/blob/007d9682dc1e757ba081601b802c9ee14e27e8b6/run_nerf.py#L970

**Comment by XTU-PR-LAB** [comment]
Hi,
   The photometric loss is written at line 941 of run_nerf.py. 
Best regards!
Shu Chen
Xiangtan University.
















At 2022-10-07 00:33:25, "Mostafa Elhashash" ***@***.***> wrote:

Hi,

Thanks for sharing the code.

Equation (6) in the paper should be a photometric loss. However, after checking the codes, I found that this line compute reprojection error not a photometric error. Am I missing something?

https://github.com/XTU-PR-LAB/SaNerf/blob/007d9682dc1e757ba081601b802c9ee14e27e8b6/run_nerf.py#L970

**Comment by melhashash** [comment]
I think you misunderstood my question, I am talking about Equation (6), which is implemented as reprojection error not photometric error as mentioned in the manuscript.

**Comment by XTU-PR-LAB** [comment]
It's true that the reprojection error is not a photometric error. the reprojection error is formulated as Eq. (7).
















At 2022-10-09 11:02:49, "Mostafa Elhashash" ***@***.***> wrote:

I think you misunderstood my question, I am talking about Equation (6), which is implemented as reprojection error not photometric error as mentioned in the manuscript.

**Comment by melhashash** [comment]
The loss function should be the sum of 3 terms namely:
1. Photometric loss (regular NeRF). Eq(1)
2. Photometric loss for sift points. Eq(6)
3. Distance between 3D points corresponding to sift points. Eq(7)

If my understanding is correct, could you please point to me where did you implement each?

**Comment by XTU-PR-LAB** [comment]
1. and 2. are combined into Eq(6), and implemented at line 941 of run_nerf.py.

**Comment by melhashash** [comment]
If this is the case then why you have both project_loss0 and   epipolar_loss0 in these two lines?

https://github.com/XTU-PR-LAB/SaNerf/blob/007d9682dc1e757ba081601b802c9ee14e27e8b6/run_nerf.py#L966

https://github.com/XTU-PR-LAB/SaNerf/blob/007d9682dc1e757ba081601b802c9ee14e27e8b6/run_nerf.py#L970

**Comment by XTU-PR-LAB** [comment]
coarse to fine. please read the original paper of NeRF.

**Comment by melhashash** [comment]
I am not talking about the coarse to fine for nerf. I am talking about two loss terms you added to nerf. You named them epipolar loss and project loss. I am not sure if these two losses are both mentioned in your manuscript. You first said 1 and 2 is together added in line941. Then what are these epipolar loss and project loss?!

**Comment by XTU-PR-LAB** [comment]
project_loss is not used becuase project_weight =0. the project_loss is only for test purpose, and i forgot to delete in the release version.

**Comment by melhashash** [comment]
I see. Thanks for answering my question.
